# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28a00dea895177ccdb52f1e0bb92a1eb2554c81712df3a194d4850fe9a19dd2cc4498e5513a3ba430eead53c4a9667c2bc8d46076edeca1d8597383bab4a2e51

test:
  secret_key_base: d270edfba0f8cb9ce52b06a1917076d6692e7fac2254ed1923c7d018b69e087dc4f3c9f6653d90e83ec5c820d1a51fc4f80ce67ba40ebdec75ba8ad0a95312b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
